import React from 'react'

const Events = () => {
  return (
    <div>
        <h1>
            Event<h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1><h1>
            Events
        </h1>s
        </h1>
    </div>
  )
}

export default Events